### What is Numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
import numpy as np

In [2]:
# np.array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
# 2D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
# 3D 
c = np.array([[[1,2],[3,4],[5,6]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]]]


In [6]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [7]:
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [8]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [9]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [12]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [13]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
# np.ones
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
# np.zeros
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# np.random
np.random.random((3,4))

array([[0.11405635, 0.87554362, 0.13565137, 0.09052417],
       [0.54434485, 0.39347588, 0.37698836, 0.8408164 ],
       [0.43139546, 0.26118634, 0.14041584, 0.80650242]])

In [19]:
# np.linspace
np.linspace(1,12,3)

array([ 1. ,  6.5, 12. ])

In [20]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [21]:
# np.identity
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [22]:
# np.eye
np.eye(2)

array([[1., 0.],
       [0., 1.]])

### Array Attributes

In [23]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)

In [24]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [26]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [27]:
# ndim
a1.ndim

1

In [28]:
a2.ndim

2

In [29]:
a3.ndim

3

In [30]:
# shape
a1.shape

(10,)

In [31]:
a2.shape

(3, 4)

In [32]:
a3.shape

(2, 2, 2)

In [33]:
# size
a1.size

10

In [34]:
a2.size

12

In [35]:
a3.size

8

In [36]:
# itemsize
a3.itemsize

4

In [37]:
a1.itemsize

4

In [38]:
a2.itemsize

8

In [39]:
# dtype
a1.dtype

dtype('int32')

In [40]:
a2.dtype

dtype('float64')

In [41]:
a3.dtype

dtype('int32')

### Changing Datatype

In [42]:
# astype
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [43]:
a3.astype(float)

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

### Array Operations

In [44]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [45]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [47]:
# scaler operation
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [49]:
# relational 
a2>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [50]:
# vector operation
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [52]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### Array Functions

In [53]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

In [54]:
a1

array([[99., 81., 66.],
       [79., 23., 70.],
       [89., 66., 42.]])

In [55]:
# max
np.max(a1)

99.0

In [56]:
np.max(a1,axis=1)

array([99., 79., 89.])

In [57]:
# min
np.min(a1)

23.0

In [58]:
# sum
np.sum(a1)

615.0

In [59]:
# prod
np.prod(a1)

1.660735039787208e+16

In [60]:
# mean
np.mean(a1)

68.33333333333333

In [61]:
# median
np.median(a1)

70.0

In [62]:
# std
np.std(a1)

22.120880030716076

In [63]:
# var
np.var(a1)

489.3333333333333

In [64]:
# trigonometric functions
np.sin(a1)

array([[-0.99920683, -0.62988799, -0.02655115],
       [-0.44411267, -0.8462204 ,  0.77389068],
       [ 0.86006941, -0.02655115, -0.91652155]])

In [65]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [66]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [68]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [69]:
# log 
np.log(a1)

array([[4.59511985, 4.39444915, 4.18965474],
       [4.36944785, 3.13549422, 4.24849524],
       [4.48863637, 4.18965474, 3.73766962]])

In [70]:
# exp
np.exp(a1)

array([[9.88903032e+42, 1.50609731e+35, 4.60718663e+28],
       [2.03828107e+34, 9.74480345e+09, 2.51543867e+30],
       [4.48961282e+38, 4.60718663e+28, 1.73927494e+18]])

In [71]:
# round
np.random.random((3,2)) * 100

array([[18.4457108 ,  0.88209703],
       [76.83609441, 29.08887798],
       [82.38088804, 50.39873077]])

In [72]:
np.round(np.random.random((3,2)) * 100)

array([[54., 86.],
       [52., 24.],
       [45., 46.]])

In [73]:
# ceil
np.ceil(np.random.random((3,2)) * 100)

array([[85., 58.],
       [64., 72.],
       [65., 13.]])

In [74]:
# floor
np.floor(np.random.random((3,2)) * 100)

array([[19., 97.],
       [98., 89.],
       [43., 61.]])

### Indexing

In [75]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3= np.arange(8).reshape(2,2,2)

In [76]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
a1[-1]

9

In [78]:
a1[0]

0

In [79]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [80]:
a2[1,2]

6.0

In [81]:
a2[2,3]

11.0

In [82]:
a2[1,0]

4.0

In [83]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [84]:
a3[1,0,1]

5

In [85]:
a3[0,1,0]

2

In [86]:
a3[0,0,0]

0

In [87]:
a3[1,1,0]

6

### Slicing

In [88]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
a1[2:5]

array([2, 3, 4])

In [90]:
a1[2:5:2]

array([2, 4])

In [91]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [92]:
a2[0]

array([0., 1., 2., 3.])

In [93]:
a2[:,2]

array([ 2.,  6., 10.])

In [94]:
a2[1:,1:3]

array([[ 5.,  6.],
       [ 9., 10.]])

In [95]:
a2[::2,::3]

array([[ 0.,  3.],
       [ 8., 11.]])

In [96]:
a2[::2,1::2]

array([[ 1.,  3.],
       [ 9., 11.]])

In [97]:
a2[1,::3]

array([4., 7.])

In [98]:
a2[:2,1:]

array([[1., 2., 3.],
       [5., 6., 7.]])

In [99]:
a2[::2,1::2]

array([[ 1.,  3.],
       [ 9., 11.]])

In [100]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [101]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [102]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [103]:
a3[0,1]

array([3, 4, 5])

In [104]:
a3[1,:,1]

array([10, 13, 16])

In [105]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [106]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

### Iteration On Numpy

In [107]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [109]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [110]:
for i in a2:
    print(i)

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [111]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [112]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [113]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [114]:
# reshape
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
# transpose
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [116]:
a2.transpose()

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [117]:
a2.T

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [118]:
# ravel
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [119]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [120]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [121]:
a2.ravel()

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

### Stacking

In [122]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [123]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [125]:
# horizontal stacking
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [126]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [127]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [128]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [129]:
# horizontal splitting
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [130]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [131]:
np.hsplit(a4,5) # Equal division should be there

ValueError: array split does not result in an equal division

In [132]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [133]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [134]:
np.vsplit(a4,2) # Equal division should be there

ValueError: array split does not result in an equal division